import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

// Regenerates the MECHANICAL facts in docs/CURRENT_STATE.md — the bits that rot
// fastest (migration count, tables, routes, test count) and are pure repo
// introspection. It rewrites only the block between the AUTOGEN markers; the
// judgment sections (traps, known gaps, in-flight, architecture prose) are
// hand-written and never touched. Run: `npm run docs:refresh`. The paired
// `docs:check` (scripts/docs-check.ts) fails loudly if this block drifts from
// reality — same spirit as db:check. See docs/DECISIONS.md ("self-maintaining
// docs"). Intent lives in the spec and is NEVER auto-synced — only reality is.

const ROOT = process.cwd();
const START = "<!-- AUTOGEN:START (npm run docs:refresh) — do not edit by hand -->";
const END = "<!-- AUTOGEN:END -->";

function migrations() {
  const files = readdirSync(join(ROOT, "drizzle")).filter((f) => f.endsWith(".sql")).sort();
  const expected = Number(
    /EXPECTED_MIGRATIONS\s*=\s*(\d+)/.exec(readFileSync(join(ROOT, "src/lib/migrationStatus.ts"), "utf8"))?.[1] ?? "0"
  );
  return { count: files.length, latest: files.at(-1)?.replace(".sql", "") ?? "(none)", expected };
}

function tables() {
  const src = readFileSync(join(ROOT, "src/db/schema.ts"), "utf8");
  return [...src.matchAll(/pgTable\("([a-z_]+)"/g)].map((m) => m[1]);
}

function routes() {
  const base = join(ROOT, "src/app/api");
  const out: Array<{ path: string; methods: string[] }> = [];
  const walk = (dir: string, rel: string) => {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      const abs = join(dir, e.name);
      if (e.isDirectory()) walk(abs, `${rel}/${e.name}`);
      else if (e.name === "route.ts") {
        const src = readFileSync(abs, "utf8");
        const methods = [...src.matchAll(/export async function (GET|POST|PATCH|DELETE|PUT)/g)].map((m) => m[1]);
        out.push({ path: rel || "/", methods });
      }
    }
  };
  walk(base, "");
  return out.sort((a, b) => a.path.localeCompare(b.path));
}

function testCount() {
  const dir = join(ROOT, "src");
  let files = 0;
  let cases = 0;
  const walk = (d: string) => {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const abs = join(d, e.name);
      if (e.isDirectory()) walk(abs);
      else if (/\.test\.ts$/.test(e.name)) {
        files += 1;
        const src = readFileSync(abs, "utf8");
        cases += [...src.matchAll(/\b(it|test)(\.\w+)?\(/g)].length;
      }
    }
  };
  walk(dir);
  return { files, cases };
}

function storeFns() {
  const src = readFileSync(join(ROOT, "src/lib/sessionStore.ts"), "utf8");
  return [...src.matchAll(/export (?:async )?function ([a-zA-Z]+)/g)].map((m) => m[1]).filter((n) => !n.startsWith("_"));
}

const m = migrations();
const t = testCount();
const block = [
  START,
  "",
  `_Snapshot generated by \`npm run docs:refresh\` — mechanical facts only. Last run reflects the working tree at generation time._`,
  "",
  `- **Migrations:** ${m.count} on disk (latest \`${m.latest}\`); \`EXPECTED_MIGRATIONS = ${m.expected}\`.`,
  `- **Tests:** ~${t.cases} cases across ${t.files} \`*.test.ts\` files.`,
  "",
  `**Tables (${tables().length}):** ${tables().map((x) => `\`${x}\``).join(", ")}`,
  "",
  "**API routes:**",
  "",
  "| Route | Methods |",
  "|---|---|",
  ...routes().map((r) => `| \`/api${r.path}\` | ${r.methods.join(", ") || "—"} |`),
  "",
  `**\`sessionStore.ts\` exports (the offline engine):** ${storeFns().map((f) => `\`${f}\``).join(", ")}`,
  "",
  END,
].join("\n");

const docPath = join(ROOT, "docs/CURRENT_STATE.md");
const doc = readFileSync(docPath, "utf8");
if (!doc.includes(START) || !doc.includes(END)) {
  console.error(`✗ docs/CURRENT_STATE.md is missing the AUTOGEN markers. Add:\n${START}\n${END}\nwhere the machine-facts block should live.`);
  process.exit(1);
}
const next = doc.replace(new RegExp(`${escapeRe(START)}[\\s\\S]*?${escapeRe(END)}`), block);
writeFileSync(docPath, next);

// Emit the facts as JSON too, so docs-check can compare without re-parsing prose.
writeFileSync(
  join(ROOT, "docs/.state-facts.json"),
  JSON.stringify({ migrations: m, tests: t, tables: tables().length, routes: routes().length }, null, 2) + "\n"
);

console.log(`✓ Refreshed CURRENT_STATE.md AUTOGEN block: ${m.count} migrations, ${tables().length} tables, ${routes().length} routes, ~${t.cases} tests.`);

function escapeRe(s: string) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
